language:
- node_js
node_js:
- '0.12'
env:
  global:
    - ON_CI=true
branches:
  only:
  - master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
- npm install
script:
- npm run code-checks
- npm run test:ci
- npm run check-coverage
- npm run build
